### ISSUE TITLE
Add example: NewConversationHandler with CallbackQuery

### ISSUE THREAD

**Issue by fresonn** [and3rson/telemux#3]
Hi, awesome lib and you've got start from me!
But I don't get how to use "ConversationHandler" with callback from inline buttons.
Could you add it to examples?

**Comment by and3rson** [comment]
Hi, thanks for the feedback!

There is an example of using `ConversationHandler` here: https://github.com/and3rson/telemux/blob/v2/examples/album_conversation/main.go

Please let me know if it's missing something!

**Comment by fresonn** [comment]
Regarding the example:
What if the image will get inline buttons when we try to view them
```go
....ReplyMarkup = tgbotapi.NewInlineKeyboardMarkup(
	tgbotapi.NewInlineKeyboardRow(
		tgbotapi.NewInlineKeyboardButtonData("Delete", "/delete " + imageId)
		// some other actions
	))
```
Then, callback data should be inside a `tm.IsCallbackQuery()`
I would like to process these callbacks from buttons and continue working in `NewConversationHandler`
But as I understand, I can't handle this inside the conversation handler like below
```go
[]*tm.Handler{
      tm.NewHandler(tm.IsCallbackQuery(), func(u *tm.Update) {      
	      fmt.Println("local callback") // it doesn't invoke
      }),
},
```
Maybe I'm not on the right way(I've not developed telegram bots before)? 
Shall I process `tm.IsCallbackQuery()` in global mux handler?

**Comment by and3rson** [comment]
You're on the right track.

Think of conversation as a group of handlers, only one of which is executed based on the state.
The initial state of every conversation is an empty string (`""`). Additionally, there are "default" handlers passed in as fourth argument which is processed when no matching handler was found in the current state.

There are several reasons why your print is not invoking:
- The update might have been consumed by one of the handlers inside conversation
- The conversation has finished (switched to empty string state) and is considered "inactive".
Are you getting any messages like "unknown command" etc when you try to click your Delete button?

For what you're trying to do, it seems like it makes sense to move the callback query handler out of the ConversationHandler. The reason for this is that the user might "end" the conversation, then scroll to an older message and click a button there. This update will be ignored because the handler which processes callback queries is inside the conversation (which is inactive).

Let me know if that helps! Otherwise please feel free to post your entire code so that we can figure it out.

**Comment by fresonn** [comment]
> This update will be ignored because the handler which processes callback queries is inside the conversation (which is inactive).

I got it. Likely a user would not like to see broken buttons and I should process that logic on top level handler.
Oh 🤦‍♂️..  it looks like I need to rethink my callback handling.

Btw. 
Can I use the callback handler in the conversation chain until calling `u.PersistenceContext.SetState("")`?

**Comment by and3rson** [comment]
@Vlad-Shevliakov Sure, it should work. Now that I think of it, you can also keep the callback handler in `defaults` array: these handlers are executed [unless the state is an empty string](https://github.com/and3rson/telemux/blob/v2/handlers.go#L205) which means your callback handler will be executed for all callback queries while the conversation is still active. Once state changes to empty string, default handlers will not be executed.

**Comment by fresonn** [comment]
Thanks for your concernment, really. I'm rewriting callback logic, and it works fine (for that moment)
